vim.keymap.set("i", "jj", "<Esc>", { noremap = true, silent = true })
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { silent = true })
vim.keymap.set("n", "q", "<Nop>", { silent = true }) -- disable macros
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { silent = true })
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set("n", "<CR>", "<CR><Cmd>cclose<CR>", { buffer = false, noremap = false, silent = true })
vim.keymap.set("n", "<cr>", "ciw")
vim.keymap.set("i", "<C-BS>", "<Esc>cvb", {})
vim.keymap.set("n", "H", "^", { noremap = true, silent = true })
vim.keymap.set("o", "H", "^", { noremap = true, silent = true })
vim.keymap.set("x", "H", "^", { noremap = true, silent = true })
vim.keymap.set("n", "L", "$", { noremap = true, silent = true })
vim.keymap.set("o", "L", "$", { noremap = true, silent = true })
vim.keymap.set("x", "L", "$", { noremap = true, silent = true })
vim.keymap.set("n", "U", "<C-r>")
