require("plugins.comment")
require("plugins.harpoon")
require("plugins.lsp")
require("plugins.packer")
require("plugins.telescope")
require("plugins.tree")
require("plugins.treesitter")
require("plugins.undotree")
